improve the formulate script entirely

diff --git a/formulate b/formulate
--- a/formulate
+++ b/formulate
@@ -1,16 +1,12 @@
 #!/bin/bash
-# shellcheck disable=SC2001
 set -euo pipefail
+shopt -s extglob
 
 cmdname="$(basename "${BASH_SOURCE[0]}")"
 version=0.0.7
 
-report-log() {
+abort() {
   echo "$1" >&2
-}
-
-report-error() {
-  echo "$cmdname: $1" >&2
   exit 1
 }
 
@@ -18,194 +14,124 @@ usage() {
   echo "Usage: $cmdname create user/name or $cmdname update name.rb"
 }
 
-git-api() {
-  url=$1
-  report-log "Fetching $url"
-  token=$(git config --global github.token || :)
-  authorization=()
-  if [[ -n $token ]]; then
-    authorization=(-H "Authorization: token $token")
+github-api() {
+  local url params token
+  url="https://api.github.com$1"
+  echo "Fetching: $url" >&2
+  params=()
+  if token="$(git config --global github.token)"; then
+    params+=(-H "Authorization: token $token")
   fi
-  curl "${authorization[@]:-}" -s "$url"
+  curl -sSf ${params[@]:+"${params[@]}"} "$url" 2> >(sed 's/^/Got error: /' >&2)
 }
 
-get-latest-json() {
-  target=$1
-  json=$(git-api "https://api.github.com/repos/$target/releases/latest")
-  if ! echo "$json" | grep '"message".*"Not Found"' > /dev/null; then
-    echo "$json"
-    return
-  fi
-  json=$(git-api "https://api.github.com/repos/$target/tags")
-  if ! echo "$json" | grep '"message".*"Not Found"' > /dev/null; then
-    echo "$json"
-    return
-  fi
-  report-error "failed to get the latest release"
+get-latest-release() {
+  github-api "/repos/$1/releases/latest" || github-api "/repos/$1/tags" | jq -e 'try .[0]' ||
+    abort "Failed to get the latest release: $1"
 }
 
-find-latest-version() {
-  json=$1
-  version=$(echo "$json" | sed -n '/"tag_name"/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
-  if [[ $version != "" ]]; then
-    echo "${version##v}"
-    return
-  fi
-  version=$(echo "$json" | sed -n '/"name"/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
-  if [[ $version != "" ]]; then
-    echo "${version##v}"
-    return
-  fi
-  report-error "failed to get version: $json"
+get-latest-version() {
+  jq -e -r 'try (.tag_name // .name | sub("^v"; ""))' ||
+    abort "Failed to get the latest version"
 }
 
-find-download-url() {
-  target=$1
-  json=$2
-  url=$(echo "$json" | sed -n '/browser_download_url.*darwin/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
-  if [[ $url != "" ]]; then
-    echo "$url"
-    return
-  fi
-  url=$(echo "$json" | sed -n '/browser_download_url/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
-  if [[ $url != "" ]]; then
-    echo "$url"
-    return
-  fi
-  if echo "$json" | grep '"zipball_url"' > /dev/null; then
-    echo "$json" | sed -n '/"zipball_url"/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1
-    return
-  fi
-  report-error "failed to get download url: $json"
+get-download-url() {
+  jq -e -r 'try (first(.assets[].browser_download_url | select(test("darwin")))? // .zipball_url)' ||
+    abort "Failed to get the download URL"
 }
 
-get-target-name() {
-  target=$1
-  echo "${target##*/}"
-}
-
-get-sha256() {
-  url=$1
-  report-log "Fetching $url"
-  if ! shasum=$(curl -L -f "$url" | sha256sum | cut -f1 -d ' '); then
-    report-error "failed to get sha256 sum: $url"
-  fi
-  report-log "Got sha256sum: $shasum"
-  echo "$shasum"
+get-sha256-checksum() {
+  echo "Fetching: $1" >&2
+  curl -sSfL "$1" | sha256sum | cut -d ' ' -f1 | tee >(sed 's/^/Got SHA-256 checksum: /' >&2) ||
+    abort "Failed to get the SHA-256 checksum: $1"
 }
 
 create() {
-  target=$1
-  name=$(get-target-name "$target")
-  formula_name=$(echo "$name" | perl -pe 's/(^|-)([a-z])/uc($2)/ge')
-  output="$name.rb"
-  report-log "Creating $output"
-  json=$(get-latest-json "$target")
-  version=$(find-latest-version "$json")
-  report-log "Found version $version"
-  url=$(find-download-url "$target" "$json")
-  sha256=$(get-sha256 "$url")
-  homepage="https://github.com/$target"
-  git_url="https://github.com/$target.git"
-  cat > "$output" <<EOF
-class $formula_name < Formula
-  homepage '$homepage'
+  local repository bin_name formula release version url
+  repository="$1"
+  bin_name="${repository##*/}"
+  formula="$bin_name.rb"
+  echo "Creating: $formula" >&2
+  release="$(get-latest-release "$repository")"
+  version="$(get-latest-version <<<"$release")"
+  echo "Found version: $version" >&2
+  url="$(get-download-url <<<"$release")"
+  cat >"$formula" <<EOF
+class $(perl -pe 's/(^|-)(\w)/\U$2/g' <<<"$bin_name") < Formula
+  homepage 'https://github.com/$repository'
   version '$version'
   url '$url'
-  sha256 '$sha256'
-  head '$git_url'
+  sha256 '$(get-sha256-checksum "$url")'
+  head 'https://github.com/$repository.git'
 
   def install
-    bin.install '$name'
+    bin.install '$bin_name'
   end
 
   test do
-    system "#{bin}/$name", '--version'
+    system "#{bin}/$bin_name", '--version'
   end
 end
 EOF
-  report-log "Created $output"
-}
-
-get-target-from-formula() {
-  target_file=$1
-  sed -n "/homepage.*github.com/s/^.*github.com\/\\(.*\\)'.*/\\1/gp" < "$target_file" | head -n1
-}
-
-get-version-from-formula() {
-  target_file=$1
-  sed -n "/^ *version /s/^.*version *'\\(.*\\)'.*/\\1/gp" < "$target_file" | head -n1
+  echo "Created: $formula" >&2
 }
 
 update() {
-  output=$1
-  report-log "Updating $output"
-  target=$(get-target-from-formula "$output")
-  if [[ $target == "" ]]; then
-    report-error "failed to find target: $output"
+  local formula repository current_version release version line url
+  formula="$1"
+  echo "Updating: $formula" >&2
+  if ! repository="$(sed -n -E '/^ *homepage /s/.*github\.com\/(.*)'\''.*/\1/p' "$formula" | head -n1 | grep ^)"; then
+    abort "Failed to find the repository: $formula"
   fi
-  current_version=$(get-version-from-formula "$output")
-  if [[ $current_version == "" ]]; then
-    report-error "failed to find version: $output"
+  if ! current_version="$(sed -n -E '/^ *version /s/.*'\''(.*)'\''.*/\1/p' "$formula" | head -n1 | grep ^)"; then
+    abort "Failed to find the current version: $formula"
   fi
-  name=$(get-target-name "$target")
-  json=$(get-latest-json "$target")
-  version=$(find-latest-version "$json")
-  if [[ $current_version == "$version" ]]; then
-    report-log "Already the latest version $version"
-    exit 0
+  release="$(get-latest-release "$repository")"
+  version="$(get-latest-version <<<"$release")"
+  if [[ "$current_version" == "$version" ]]; then
+    echo "Already the latest version: $version" >&2
+    return
   fi
-  report-log "Found version $version"
-  url=""
-  outtmp=$(mktemp -t "$name.XXXXXXXX")
-  trap 'rm -rf $outtmp' EXIT SIGHUP SIGINT SIGQUIT SIGTERM
+  echo "Found version: $version" >&2
+  temp_file="$(mktemp)" # global variable for trap
+  trap 'rm -rf "$temp_file"' EXIT
   while IFS= read -r line; do
-    if echo "$line" | grep '^ *version ' > /dev/null; then
-      line=$(echo "$line" | sed 's/[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}/'"$version"'/')
-    elif echo "$line" | grep '^ *url ' > /dev/null; then
-      line=$(echo "$line" | sed 's/[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}/'"$version"'/g')
-      url=$(echo "$line" | sed "s/^.*'\\(.*\\)'.*$/\\1/")
-    elif echo "$line" | grep '^ *sha256 ' > /dev/null; then
-      if [[ $url == "" ]]; then
-        report-error "url not found: $line"
-      fi
-      sha256=$(get-sha256 "$url")
-      line=$(echo "$line" | sed "s/'.*'/'$sha256'/")
-    fi
+    case "$line" in
+    *( )version\ *)
+      line="$(sed -E 's/[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}/'"$version"'/' <<<"$line")"
+      ;;
+    *( )url\ *)
+      line="$(sed -E 's/[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}/'"$version"'/g' <<<"$line")"
+      url="$(cut -d "'" -f2 <<<"$line")"
+      ;;
+    *( )sha256\ *)
+      [[ -z "$url" ]] && abort "URL not found: $line"
+      line="$(sed -E "s/'.*'/'$(get-sha256-checksum "$url")'/" <<<"$line")"
+      ;;
+    esac
     echo "$line"
-  done < "$output" > "$outtmp"
-  mv "$outtmp" "$output"
-  report-log "Updated $output"
-}
-
-main() {
-  subcmd=$1
-  case "$subcmd" in
-    create)
-      create "$2"
-      ;;
-    update)
-      update "$2"
-      ;;
-    --version|-v)
-      echo "$cmdname $version"
-      ;;
-    *)
-      usage
-      report-error "unknown command: $subcmd"
-      ;;
-  esac
+  done <"$formula" >"$temp_file"
+  mv "$temp_file" "$formula"
+  echo "Updated: $formula" >&2
 }
 
 if [[ $# -lt 1 ]]; then
-  usage
-  report-error "specify command"
-elif [[ $1 != "-"* && $# -lt 2 ]]; then
-  usage
-  report-error "specify target"
+  usage && abort "$cmdname: specify command"
 elif [[ $# -gt 2 ]]; then
-  usage
-  report-error "too many arguments"
+  usage && abort "$cmdname: too many arguments"
+else
+  case "$1" in
+  create | update)
+    if [[ $# -ne 2 ]]; then
+      usage && abort "$cmdname: specify repository or formula file"
+    fi
+    "$@"
+    ;;
+  --version | -v)
+    echo "$cmdname $version"
+    ;;
+  *)
+    usage && abort "$cmdname: unknown command: $1"
+    ;;
+  esac
 fi
-
-main "$1" "${2:-}"
